### PR TITLE
Use YAML object for app configuration values

### PR DESCRIPTION
**Pull request by fiunchinho**
Same as https://github.com/giantswarm/default-apps-aws/pull/380

### CODE REVIEW

**Review by calvix — APPROVED** [review]

**Review by AndiDog — APPROVED** [review]
/run cluster-test-suites

**Comment by erkanerol** [comment]
e2e tests are working now. Feel free to rebase&update this PR.

**Comment by erkanerol** [comment]
FINALLY 🥳

**Pull request merged**
