### PR TITLE
Generate schema docs in the project

### PR DESCRIPTION
**Pull request by pipo02mix**
This PR:

Towards https://github.com/giantswarm/giantswarm/issues/29628

I want to add a Chart README to be embedded in our docs based on the [schemadocs](https://github.com/giantswarm/schemadocs) project

### Checklist

- [x] Update changelog in CHANGELOG.md.
- [x] Make sure `values.yaml` and `values.schema.json` are valid.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by erkanerol** [comment]
We don't have any description :( 

@pipo02mix do we have a check to verify README is up-to-date? e.g. https://github.com/giantswarm/cluster-api-provider-vsphere-app/blob/main/.github/workflows/check_generated.yaml#L18

**Comment by pipo02mix** [comment]
I added the description

Ideally, we add this as part of the workflow yes, but first I want to run it manually to check the state before automate it

**Comment by pipo02mix** [comment]
it failed because promtail, weird :/

Screenshot 2024-02-12 at 14 49 58

**Comment by erkanerol** [comment]
@pipo02mix I am on the promtail fix. See https://github.com/giantswarm/giantswarm/issues/29816

**Comment by pipo02mix** [comment]
@erkanerol thx, is ok to approve?

**Review by erkanerol — APPROVED** [review]

**Pull request merged**
