### PR TITLE
Add k8s-dns-node-cache app

### PR DESCRIPTION
**Pull request by kopiczko**

### CODE REVIEW

**Comment by kopiczko** [comment]
Tested manually on `glippy` WC

**Review by mcharriere — APPROVED** [review]

**Comment by erkanerol** [comment]
Please don't re-run the tests. We have an incident in Azure now.

**Comment by erkanerol** [comment]
Tests failed with this error. FYI. 

`{"level":"info","ts":"2024-03-26T11:53:40Z","msg":"Checking if App status for t-48d3v26ob47e0chw4w-k8s-dns-node-cache is equal to 'deployed': invalid-manifest"}`

**Pull request merged**
