### PR TITLE
add txt wildcard replacement to external-dns

### PR DESCRIPTION
**Pull request by mcharriere**
Signed-off-by: Matias Charriere <matias@giantswarm.io>

This PR:

- Add argument replacing the wildcard character. 

Towards https://github.com/giantswarm/giantswarm/issues/28848

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Comment by AndiDog** [comment]
I can't review because there's no change description or issue reference that explains why this is needed (specifically for Azure?)

**Comment by mcharriere** [comment]
Oh sorry about that @AndiDog . I'll fill in the details and put it up to standard

**Review by ubergesundheit — APPROVED** [review]

**Review by AndiDog — APPROVED** [review]

**Review by Gacko — APPROVED** [review]

**Comment by fiunchinho** [comment]
pipeline failed with `Checking if App status for t-uk567xqj0yuee5s77e-cert-manager is equal to 'deployed': pending-install`. So there seems to be a problem with `cert-manager`.

**Comment by mcharriere** [comment]
This won't be needed anymore, as we'll be adding the wildcard to the dns-operator-azure.

**Pull request closed without merging**
