### PR TITLE
enable kube proxy cilium replacement

### PR DESCRIPTION
**Pull request by primeroz**
Towards https://github.com/giantswarm/giantswarm/issues/25360

- enable kube proxy replacement and update cilium to latest version
- Update cilium to 0.9.3 

This PR:

- adds/changes/removes etc

### Testing

Description on how default-apps-azure can be tested.

- [ ] fresh install works
  - [ ] AWS
  - [ ] Azure
  - [ ] KVM
- [ ] upgrade from previous version works
  - [ ] AWS
  - [ ] Azure
  - [ ] KVM

#### Other testing

Description of features to additionally test for default-apps-azure installations.

- [ ] check reconciliation of existing resources after upgrading
- [ ] X still works after upgrade
- [ ] Y is installed correctly

### Checklist

- [ ] Update changelog in CHANGELOG.md.
- [ ] Make sure `values.yaml` and `values.schema.json` are valid.

### Trigger e2e tests

/run cluster-test-suites

### CODE REVIEW

**Review by bavarianbidi — APPROVED** [review]

**Review by nprokopic — APPROVED** [review]

**Comment by primeroz** [comment]
for some reason when a Workload cluster is created through `cluster-test-suites` the `baseDomain` is different from a WC created by hand 

```
➜ helm -n org-nikola get values np1016-default-apps | grep -i basedomain
baseDomain: azuretest.gigantic.io

➜ helm -n org-t-esyobi8 get values t-k7sk8ll-default-apps | grep -i basedomain
baseDomain: t-k7sk8ll.azuretest.gigantic.io
```

this is causing the definition of `ApiServer` for cilium to break

**Pull request merged**
